#  ------------------------------------------------------------
#  |                      RealChat plugin                     |
#  |                                                          |
#  |           Author : huda0209                              |
#  |                                        |
#  |   GitHub : https://github.com/AzisabaNetwork/RealChat    |
#  |                     ran by paper 1.13                    |
#  ------------------------------------------------------------


PluginMode: true

CanChatRange: 15
NoPlayerChatRangeError: true

NoGlobalList:
  - uuid
  -